name: Deploy after push

on:
    push:
      branches: [ "master" ]
    workflow_dispatch:

env:
  SSH_KEY_FILE_DIR: .keys
  SSH_KEY_FILE_PATH: .keys/deploy_key.pem

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Create deploy key file
              run: |
                mkdir ${{env.SSH_KEY_FILE_DIR}}
                echo "${{secrets.SSH_DEPLOY_KEY}}" > ${{env.SSH_KEY_FILE_PATH}}
                chmod 600  ${{env.SSH_KEY_FILE_PATH}}

            - name: Deploy to Main Server
              run: |
                rsync -have "ssh -i  ${{env.SSH_KEY_FILE_PATH}}" --exclude=".keys" . ${{secrets.SSH_DEPLOY_USER}}@${{secrets.SSH_MAIN_HOST}}:${{secrets.DEPLOY_PATH}}
            - name: Deploy to backup Server
              run: |
                rsync -have "ssh -i  ${{env.SSH_KEY_FILE_PATH}}" --exclude=".keys" . ${{secrets.SSH_DEPLOY_USER}}@${{secrets.SSH_BACKUP_HOST}}:${{secrets.DEPLOY_PATH}}

            - name: Clean deply key file
              run: |
                rm -rf ${{env.SSH_KEY_FILE_DIR}}


